<<<<<<< HEAD
<<<<<<< HEAD
import type { Metadata } from 'next';
import { Kumbh_Sans } from 'next/font/google';
import './globals.css';

const kumbhSans = Kumbh_Sans({
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata: Metadata = {
  title: {
    template: '%s | Handcrafted Haven',
    default: 'Home',
  },
  description: 'Handcrafted Haven is an innovative web application that aims to provide a platform for artisans and crafters to showcase and sell their unique handcrafted items.',
=======
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
>>>>>>> f58ac01 (completed team setup)
=======
import type { Metadata } from 'next';
import { Kumbh_Sans } from 'next/font/google';
import './globals.css';

const kumbhSans = Kumbh_Sans({
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata: Metadata = {
  title: {
    template: '%s | Handcrafted Haven',
    default: 'Home',
  },
  description: 'Handcrafted Haven is an innovative web application that aims to provide a platform for artisans and crafters to showcase and sell their unique handcrafted items.',
>>>>>>> 8026466 (Customized TailwindCSS colors, added google font and set metadata)
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
<<<<<<< HEAD
<<<<<<< HEAD
      <body className={kumbhSans.className}>{children}</body>
=======
      <body>{children}</body>
>>>>>>> f58ac01 (completed team setup)
=======
      <body className={kumbhSans.className}>{children}</body>
>>>>>>> 8026466 (Customized TailwindCSS colors, added google font and set metadata)
    </html>
  )
}